apiVersion: batch/v1
kind: Job
metadata:
  name: job-train
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: train
    spec:
      restartPolicy: Never
      containers:
        - name: train
          image: aiad-fesi-crew-kedro:v5   # <-- latest image with conf included
          imagePullPolicy: IfNotPresent
          env:
            - name: PIPELINE
              value: "training"
            - name: KEDRO_ENV
              value: "base"
          volumeMounts:
            - name: data
              mountPath: /project/data     # mount your PVC data here
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: plantml-data-pvc    # same PVC used before
